### ISSUE TITLE
Support UNION clause

### ISSUE THREAD

**Issue by albin3** [JavaScriptor/js-sql-parser#2]
https://dev.mysql.com/doc/refman/8.0/en/union.html

**Comment by shtse8** [comment]
Can it support dash quote? like SELECT `attribute` FROM `table`

**Comment by albin3** [comment]
@shtse8 supported at js-sql-parser@1.0.2

**Comment by morenoh149** [comment]
which commit added this functionality? https://github.com/JavaScriptor/js-sql-parser/commit/6d526bdf76097cdabed35a6083e635ccfe17dd4c ?

**Comment by albin3** [comment]
@morenoh149 UNION feature not supported yet.

**Comment by yuemingl** [comment]
Any update for union? I think it is important for data set generation from mixed sources in some applications.

**Comment by yuemingl** [comment]
This is a working change:
sqlParser.jison
UNION return 'UNION'
selectClause
  : SELECT 
      distinctOpt
      highPriorityOpt
      maxStateMentTimeOpt
      straightJoinOpt
      sqlSmallResultOpt
      sqlBigResultOpt
      sqlBufferResultOpt
      sqlCacheOpt
      sqlCalcFoundRowsOpt
      selectExprList
      selectDataSetOpt
      unionStatementsOpt
      {
        $$ = {
          type: 'Select',
          distinctOpt: $2,
          highPriorityOpt: $3,
          maxStateMentTimeOpt: $4,
          straightJoinOpt: $5,
          sqlSmallResultOpt: $6,
          sqlBigResultOpt: $7,
          sqlBufferResultOpt: $8,
          sqlCacheOpt: $9,
          sqlCalcFoundRowsOpt: $10,
          selectItems: $11,
          from: $12.from,
          partition: $12.partition,
          where: $12.where,
          groupBy: $12.groupBy,
          having: $12.having,
          orderBy: $12.orderBy,
          limit: $12.limit,
          procedure: $12.procedure,
          updateLockMode: $12.updateLockMode,
          union: $13
        }
      }
  ;
unionStatementsOpt
    : unionStatementsOpt unionStatement { $$ = $2 }
    | { $$ = null }
    ;
unionStatement
  : UNION selectClause { $$ = {select: $2} }
  ;

main.test.js
  it ('test15', function () {
    testParser(`
      SELECT * from A 
      UNION 
      SELECT * from B 
      UNION 
      SELECT * from C
    `);
  });

For the test above, the ast looks like:
nodeType: "Main"
value:
-type: "Select"
-union:
--select:
---type: "Select"
---union:
----select:
----type: "Select"
-----union: null

**Comment by albin3** [comment]
supported since `js-sql-parser@1.0.8`

**Comment by albin3** [comment]
@morenoh149 @yuemingl Union feature has supported.
