### ISSUE TITLE
多重嵌套查询sql解析报错

### ISSUE THREAD

**Issue by sumulige** [JavaScriptor/js-sql-parser#27]
请原谅我英语不好
```sql
select
t2.xxx，
t2.xxx,
t2.xxx
from
(select t1.xxx,t1xxx,t1.xxx from tables t1 FETCH FIRST 100 rows only）t2
left join
tables t3
on t2.xxx = t3.xxx

```

var sqlParser = windows.sqlparser;
var qst = sqlParser.parse(querySql);
报错信息如下：
Uncaught Error :Parser error on line 1:
...tables t1        FETCH      F1
----------------------------
Excepting 'EOF'，',' ,

不支持DB2 的FETCH

**Comment by albin3** [comment]
@sumulige 这个报错是因为 `FETCH` 语法不支持。

目前这个库是按照mysql的语法解析的。里面不包含 `FETCH` 的语法。

语法参考： https://dev.mysql.com/doc/refman/5.7/en/select.html

**Comment by albin3** [comment]
`FETCH` grammar is not supported yet. Closing this as there is no plan to support currently.
