### ISSUE TITLE
Support string functions LEFT() and RIGHT() 

### ISSUE THREAD

**Issue by stefanreimers** [JavaScriptor/js-sql-parser#3]
Unlike other functions LEFT() and RIGHT() are not working in the selection of a query:

    `sqlParser.parse('SELECT LEFT(a, 3) FROM b')`

returns a parseError

**Comment by albin3** [comment]
@stefanreimers  supported at js-sql-parser@1.0.2 
```
sqlParser.parse('SELECT `LEFT`(a, 3) FROM b') 
```
