### ISSUE TITLE
WHERE conditions when only one Identifier

### ISSUE THREAD

**Issue by dwips** [JavaScriptor/js-sql-parser#32]
Hi 
I found something that maybe this is a bug. So when i tried the SQL query like in the picture below, it creates the AST, shouldn't it throw an error since only the Identifier specified without operator?

![image](https://user-images.githubusercontent.com/6791049/75645554-eb326200-5c78-11ea-8ab8-f31b6db65969.png)

![image](https://user-images.githubusercontent.com/6791049/75645566-fd140500-5c78-11ea-8cae-a87e31dde335.png)

Thanks a lot

**Comment by albin3** [comment]
@dwips Hi dwips, the grammar is ok in Mysql. In this case column_1 is a `identifier`, also it's an `Expressions`.  (reference, https://dev.mysql.com/doc/refman/5.7/en/expressions.html)

I tried this grammar in mysql. When column_1 is bool type, it works as `column_1 = TRUE`.

😀

**Comment by dwips** [comment]
i see
ok noted, you can close this ticket then

Thank you

**Comment by albin3** [comment]
Closing this issue.
