### ISSUE TITLE
LEFT JOIN bug

### ISSUE THREAD

**Issue by Enoch300** [JavaScriptor/js-sql-parser#34]
你好！
在使用js-sql-parser时发现一个问题:
ast = sqlParser.parse("SELECT stime, A.names, B.names FROM (SELECT stime, names FROM iaas_data.iaas_d3c0d0681cc1900) AS A LEFT JOIN (SELECT stime, names FROM iaas_data.iaas_1071f89feaa0e100) AS B ON A.stime = B.stime")

sqlParser.stringify(ast) 结果:
SELECT stime, A.names, B.names FROM (SELECT stime, names FROM iaas_data.iaas_d3c0d0681cc1900) LEFT JOIN (SELECT stime, names FROM iaas_data.iaas_1071f89feaa0e100) ON A.stime = B.stime

问题:
sqlParser.stringify(ast)后的SQL 没有 AS A  和 AS B 导致SQL错误.

**Comment by albin3** [comment]
+ js-sql-parser@1.3.0 have been released to fix this.

**Comment by albin3** [comment]
@Enoch300 版本1.3.0修复了，多谢

**Comment by Enoch300** [comment]
> @Enoch300 版本1.3.0修复了，多谢

不客气，很好用。后续有什么问题再给您反馈哈 ，感谢付出
