### ISSUE TITLE
using ' & " for column alias?

### ISSUE THREAD

**Issue by lab4quant** [JavaScriptor/js-sql-parser#40]
Hello, awesome project,
i'm using it for parsing sql query, it's great

I sometimes need to use column alias, right now we need to use "\`", is this mysql standard or something?

is it possible to add support for using `'` & `"` for column alias?

the reason being, many times in javascript, we use "\`" for long string that breaks into lines, in such case we have to escape "\`", it would be a lot more convenient if we could use  `'` or  `"`

e.g. 

```js
sql(`
select title \`Title\`,
          author \`Author\`,
 from notebook
`)
```

it would be nice to write like this:

```js
sql(`
select title 'Title',
          author "Author",
 from notebook
`)
```

**Comment by albin3** [comment]
hello there, you can just use alias without quotations.

ex:
```
sql(`
select title Title,
          author Author
 from notebook
`)
```

**Comment by lab4quant** [comment]
@albin3 , thanks, i'm aware of that, but what if the alias have space, like

```
sql(`
select title 'Title of Notebook',
          author "Notebook Author",
 from notebook
`)
```
