### ISSUE TITLE
not support <>?

### ISSUE THREAD

**Issue by shengguofeng** [JavaScriptor/js-sql-parser#6]
when I parse sql like   
select * from test where a<>1
I got this error:

sqlParser.js:414 Uncaught Error: Parse error on line 1:
...* from test where a<>1
-----------------------^
Expecting 'ALL', 'NUMERIC', 'IDENTIFIER', 'QUOTED_IDENTIFIER', 'STRING', 'EXPONENT_NUMERIC', 'HEX_NUMERIC', 'TRUE', 'FALSE', 'NULL', '(', 'CASE', '+', '-', '~', '!', 'BINARY', 'ROW', 'EXISTS', '{', 'ANY', got '>

**Comment by albin3** [comment]
fixed at js-sql-parser@1.0.5
